---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: magpie
  namespace: flux-system
spec:
  targetNamespace: magpie
  commonMetadata:
    labels:
      app.kubernetes.io/name: magpie
  path: "./Distribution/kubernetes/Magpie/magpie/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: 2024-cmpu9010-group-3
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: ext-postgres-operator
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
