FROM golang:1.23.3-bookworm@sha256:59b8183301af6dc358c9258d7b2ab0ee1a9363618552334fb3b160d454cbda72 AS build-stage

WORKDIR /app

COPY go.mod ./

RUN  go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -tags public -o /app/bin/main ./cmd/main

FROM build-stage AS test-stage
RUN go test -v ./...

FROM alpine@sha256:1e42bbe2508154c9126d48c2b8a75420c3544343bf86fd041fb7527e017a4b4a AS release-stage

RUN addgroup -S rootless_group && adduser -S rootless_user -G rootless_group

WORKDIR /

COPY --from=build-stage /app/bin/main /app/bin/main

COPY --from=build-stage /app/sql/migrations/ ./sql/migrations/

RUN chown -R rootless_user:rootless_group /app/bin/main /sql/migrations

# Install curl for healthcheck
RUN apk add --no-cache curl

EXPOSE 8080

USER rootless_user

ENTRYPOINT ["/app/bin/main"]
