definitions:
    InfinityModifier:
        format: int8
        type: integer
        x-go-package: github.com/jackc/pgx/v5/pgtype
    Login:
        properties:
            email:
                description: Email associated with the login
                type: string
                x-go-name: Email
            id:
                $ref: '#/definitions/UUID'
            passwordhash:
                description: Hashed password for security
                type: string
                x-go-name: Passwordhash
            username:
                description: Username for login
                type: string
                x-go-name: Username
        required:
            - username
            - email
            - passwordhash
        title: Login represents a user's login credentials.
        type: object
        x-go-package: github.com/2024-CMPU9010-GROUP-3/PROJECT/internal/db/public
    Point:
        required:
            - type
        title: A Point represents a single point.
        type: object
        x-go-package: github.com/twpayne/go-geom
    PointType:
        type: string
        x-go-package: github.com/2024-CMPU9010-GROUP-3/PROJECT/internal/db/public
    Text:
        properties:
            String:
                type: string
            Valid:
                type: boolean
        type: object
        x-go-package: github.com/jackc/pgx/v5/pgtype
    Timestamp:
        properties:
            InfinityModifier:
                $ref: '#/definitions/InfinityModifier'
            Time:
                format: date-time
                type: string
            Valid:
                type: boolean
        title: Timestamp represents the PostgreSQL timestamp type.
        type: object
        x-go-package: github.com/jackc/pgx/v5/pgtype
    UUID:
        properties:
            Bytes:
                items:
                    format: uint8
                    type: integer
                type: array
            Valid:
                type: boolean
        type: object
        x-go-package: github.com/jackc/pgx/v5/pgtype
    UserDetail:
        properties:
            firstname:
                description: First name of the user
                type: string
                x-go-name: Firstname
            id:
                $ref: '#/definitions/UUID'
            lastloggedin:
                $ref: '#/definitions/Timestamp'
            lastname:
                description: Last name of the user
                type: string
                x-go-name: Lastname
            profilepicture:
                $ref: '#/definitions/Text'
            registerdate:
                $ref: '#/definitions/Timestamp'
        required:
            - firstname
            - lastname
        title: UserDetail contains detailed information about a user.
        type: object
        x-go-package: github.com/2024-CMPU9010-GROUP-3/PROJECT/internal/db/public
    geom0:
        type: object
        x-go-package: github.com/twpayne/go-geom
info: {}
paths: {}
swagger: "2.0"
