//go:build public

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries_public.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	geos "github.com/twpayne/go-geos"
)

const createUser = `-- name: CreateUser :one
INSERT INTO logins (
  Username, Email, PasswordHash
) VALUES (
  $1, $2, $3
) RETURNING Id
`

type CreateUserParams struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	Passwordhash string `json:"passwordhash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Email, arg.Passwordhash)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createUserDetails = `-- name: CreateUserDetails :one
INSERT INTO user_details (
  Id, FirstName, LastName, ProfilePicture
) VALUES (
  $1, $2, $3, $4
) RETURNING Id
`

type CreateUserDetailsParams struct {
	ID             pgtype.UUID `json:"id"`
	Firstname      string      `json:"firstname"`
	Lastname       string      `json:"lastname"`
	Profilepicture pgtype.Text `json:"profilepicture"`
}

func (q *Queries) CreateUserDetails(ctx context.Context, arg CreateUserDetailsParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createUserDetails,
		arg.ID,
		arg.Firstname,
		arg.Lastname,
		arg.Profilepicture,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getPointDetails = `-- name: GetPointDetails :one
SELECT Details::jsonb FROM points
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPointDetails(ctx context.Context, id int64) ([]byte, error) {
	row := q.db.QueryRow(ctx, getPointDetails, id)
	var details []byte
	err := row.Scan(&details)
	return details, err
}

const getPointsInEnvelope = `-- name: GetPointsInEnvelope :many
SELECT Id, LongLat::geometry, Type FROM points
WHERE ST_Intersects(ST_MakeEnvelope($1::float, $2::float, $3::float, $4::float, 4326), points.LongLat)
`

type GetPointsInEnvelopeParams struct {
	X1 float64 `json:"x1"`
	Y1 float64 `json:"y1"`
	X2 float64 `json:"x2"`
	Y2 float64 `json:"y2"`
}

type GetPointsInEnvelopeRow struct {
	ID      int64      `json:"id"`
	Longlat *geos.Geom `json:"longlat"`
	Type    PointType  `json:"type"`
}

func (q *Queries) GetPointsInEnvelope(ctx context.Context, arg GetPointsInEnvelopeParams) ([]GetPointsInEnvelopeRow, error) {
	rows, err := q.db.Query(ctx, getPointsInEnvelope,
		arg.X1,
		arg.Y1,
		arg.X2,
		arg.Y2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPointsInEnvelopeRow
	for rows.Next() {
		var i GetPointsInEnvelopeRow
		if err := rows.Scan(&i.ID, &i.Longlat, &i.Type); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserDetails = `-- name: GetUserDetails :one
SELECT Id, RegisterDate, FirstName, LastName, ProfilePicture, LastLoggedIn
FROM user_details
WHERE Id = $1
LIMIT 1
`

func (q *Queries) GetUserDetails(ctx context.Context, id pgtype.UUID) (UserDetail, error) {
	row := q.db.QueryRow(ctx, getUserDetails, id)
	var i UserDetail
	err := row.Scan(
		&i.ID,
		&i.Registerdate,
		&i.Firstname,
		&i.Lastname,
		&i.Profilepicture,
		&i.Lastloggedin,
	)
	return i, err
}
