\contentsline {listing}{\numberline {1}{\ignorespaces An example of a sqlc configuration file with two targets with separate query inputs}}{9}{listing.1}%
\contentsline {listing}{\numberline {2}{\ignorespaces An example of a SQL query with annotations used by sqlc}}{11}{listing.2}%
\contentsline {listing}{\numberline {3}{\ignorespaces An example of a Go binding generated by sqlc from the SQL query in Listing \ref {listing:sqlc_query_input}}}{53}{listing.3}%
\contentsline {listing}{\numberline {4}{\ignorespaces An example of an issue template used in \textit {Magpie}}}{54}{listing.4}%
\contentsline {listing}{\numberline {5}{\ignorespaces An example of a pull request template used in \textit {Magpie}}}{54}{listing.5}%
\contentsline {listing}{\numberline {6}{\ignorespaces An example of a GitHub Actions workflow that will not work}}{54}{listing.6}%
\contentsline {listing}{\numberline {7}{\ignorespaces An example of a GitHub Actions workflow that will work}}{55}{listing.7}%
\contentsline {listing}{\numberline {8}{\ignorespaces A github action that checks the branch name (this was edited for brevity)}}{55}{listing.8}%
