# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.14.0/deployment-apps-v1.json
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-backend-deployment
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: private-backend
  template:
    metadata:
      labels:
        app: private-backend
    spec:
      containers:
        - name: private-backend
          image: ghcr.io/2024-cmpu9010-group-3/backend-private:0.12.0@sha256:6ca590174184da29ac72d7d5650b47b7b3a7c69b341ef6020fae0340229d438b
          resources: {}
          ports:
            - containerPort: 3000
          livenessProbe:
            exec:
              command: ["curl --fail http://localhost:8080/heartbeat || exit 1"]
            failureThreshold: 1
            periodSeconds: 30
          startupProbe:
            exec:
              command: ["curl --fail http://localhost:8080/heartbeat || exit 1"]
            failureThreshold: 30
            periodSeconds: 10
          env:
            - name: LOGIN
              valueFrom:
                secretKeyRef:
                  name: secret-magpie-db-user
                  key: LOGIN
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-magpie-db-user
                  key: PASSWORD
            - name: HOST
              valueFrom:
                secretKeyRef:
                  name: secret-magpie-db-user
                  key: HOST
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: secret-magpie-db-user
                  key: DATABASE_NAME

            - name: MAGPIE_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secret-magpie-db-user
                  key: MAGPIE_JWT_SECRET
