---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/2024-cmpu9010-group-3/frontend:0.6.0@sha256:5b3c81175f73d1f927d3127592f867e4fb9022841a6c8ec016743947f70c000e
          resources: {}
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: frontend-secret
                  key: Mapbox_API
            - name: NODE_ENV
              value: production
            - name: NEXT_PUBLIC_BACKEND_URL
              value: http://public-backend-service.magpie.svc.cluster.local:8080