---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/2024-cmpu9010-group-3/frontend:0.7.0@sha256:383c11ad5f5305b5b25b8cdee153b2ff554f8cb7666dd2457085a4559c1acddd
          resources: {}
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: frontend-secret
                  key: Mapbox_API
            - name: NODE_ENV
              value: production
            - name: NEXT_PUBLIC_BACKEND_URL
              value: http://public-backend-service.magpie.svc.cluster.local:8080