# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.14.0/deployment-apps-v1.json
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/2024-cmpu9010-group-3/frontend:0.9.0@sha256:87beeacaa4ff2e32618c595bd8044d5a7030f594a147c88a514de3df33c3da27
          resources: {}
          ports:
            - containerPort: 3000
          livenessProbe:
            exec:
              command:
                - curl
                - --fail
                - http://localhost:3000/
            failureThreshold: 1
            periodSeconds: 30
          startupProbe:
            exec:
              command:
                - curl
                - --fail
                - http://localhost:3000/
            failureThreshold: 30
            periodSeconds: 10
          env:
            - name: NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: frontend-secret
                  key: Mapbox_API
            - name: NODE_ENV
              value: production
            - name: NEXT_PUBLIC_BACKEND_URL
              value: http://public-backend-service.magpie.svc.cluster.local:8080
