---
    apiVersion: traefik.io/v1alpha1
    kind: IngressRoute
    metadata:
      name: frontend-ingress
      annotations:
        kubernetes.io/ingress.class: traefik-external
    spec:
      entryPoints:
        - websecure
      routes:
        - match: Host(`magpie.solonsstuff.com`)
          kind: Rule
          services:
            - name: frontend-service
              port: 80
          middlewares:
            - name: default-headers
      tls:
        secretName: solonsstuff-com-live-tls
    