apiVersion: v1
kind: Secret
metadata:
    name: frontend-secret
type: Opaque
stringData:
    Mapbox_API: ENC[AES256_GCM,data:mbdyJT8KyyZFIQYdXt884iHcy3Y4ycrugthZ9B+hlVo0qsMiwtPlvgVGMhFPRM8qnIKMloZPCVo6dFDHOb9FQr1WWwudy5j/HytZaK5gRlQNAnfV5qOfrl+dS5A1SUy+8hklvA==,iv:rXQLZJ/cYnMvwW4oazLTVkM+ed5zgxySNlUR6AtV4Bs=,tag:rIuXYinlPgaeH/QthlHAkQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13arp4yu8k7s9ck59ryj4vzedkggkp8eph6hq9ukdtcpdvnf8f9uqypjty6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpSVdpeklsYlMyTER5RjdL
            YWJibVFRNzRaVkI0T2VNZlc2RVhubWJJLzIwCktYSnQ3TlVic0kybmozQW1ZeXBt
            YWhoYWZGdkE5OCtKL0U5NkpkSEtEK2cKLS0tIDNJV3VtS3NEUmhPeTNYMURaNjEz
            V2Z1ZEUzQkVNditjR0VVWm9iTlhkc1UKb8gavdtBFdnkv2w4yjY93TrUIKrfIfGS
            VvDOUd6XI5pszAP07F8pqIxO2SApyMjxKbkdDvO/kxLlnb+dJrsUxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-19T13:08:11Z"
    mac: ENC[AES256_GCM,data:0boGC3s6aITRo1FUJwEX77OB6OsjdnaWsB/Pqr+SopVIwO0O+o/kaimWYld1y3ybHM0/PNBfr4RBY+mRC57JzBkY9S3K3zvFN92GTRelrIpsGj2FwNqYWdI0lLbkUoudpVMsF+1NUfUgfA5z9MdLxoIWaO1+BRAOJIsRdGxn5TI=,iv:gDhMHBVZTa4KphIUqTQKBfweC9Un3f8QjYwT+ZuZZqk=,tag:M/NcbwclwBQc+o72FB2z7Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
