// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "url": "https://gophercoding.com"
        },
        "version": "{{.Version}}",
        "x-logo": {
            "altText": "example logo",
            "backgroundColor": "#000000",
            "href": "https://example.com/img.png",
            "url": "https://example.com/img.png"
        }
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/private/points/": {
            "post": {
                "description": "Creates a new point in the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create new point",
                "responses": {
                    "201": {
                        "description": "Created"
                    }
                }
            }
        },
        "/v1/public/points/byRadius": {
            "get": {
                "description": "Get all points in a box around the given point",
                "produces": [
                    "application/json"
                ],
                "summary": "Points by radius",
                "parameters": [
                    {
                        "type": "number",
                        "description": "Longitude of center point",
                        "name": "long",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Latitude of center point",
                        "name": "lat",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Size of box around center point",
                        "name": "radius",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "api.gophercoding.com",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "My API documentation",
	Description:      "A collection of fun related api endpoints.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
