version: '3.8'

services:
  private-service:
    image: ghcr.io/2024-cmpu9010-group-3/backend-private:0.5.0
    container_name: private-service
    ports:
      - "8081:8080"
    networks:
      - app-network

  public-service:
    image: ghcr.io/2024-cmpu9010-group-3/backend-public:0.4.0
    container_name: public-service
    ports:
      - "8082:8080"
    networks:
      - app-network

  frontend-service:
    image: ghcr.io/2024-cmpu9010-group-3/frontend:0.1.0
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN={MAPBOX_ACCESS_TOKEN}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
