version: '3.8'

services:
  private-service:
    image: ghcr.io/2024-cmpu9010-group-3/backend-private:0.6.0
    container_name: private-backend
    ports:
      - "8081:8080"
    networks:
      - app-network
    environment:
      - MAGPIE_DB_URL=postgres://postgres:mysecretpassword@localhost:5432/postgres
      - MAGPIE_JWT_SECRET=your_jwt_secret
      - MAGPIE_JWT_EXPIRY=24h
      - MAGPIE_CORS_ALLOWED_ORIGINS=http://localhost:3000 https://localhost:3000 http://example.com
      - MAGPIE_CORS_ALLOWED_METHODS=GET POST PUT DELETE

  public-service:
    image: ghcr.io/2024-cmpu9010-group-3/backend-public:0.6.0
    container_name: public-backend
    ports:
      - "8082:8080"
    networks:
      - app-network
    environment:
      - MAGPIE_DB_URL=postgres://postgres:mysecretpassword@localhost:5432/postgres
      - MAGPIE_JWT_SECRET=your_jwt_secret
      - MAGPIE_JWT_EXPIRY=24h
      - MAGPIE_CORS_ALLOWED_ORIGINS=http://localhost:3000 https://localhost:3000 http://example.com
      - MAGPIE_CORS_ALLOWED_METHODS=GET POST PUT DELETE

  frontend-service:
    image: ghcr.io/2024-cmpu9010-group-3/frontend:0.1.0
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN={MAPBOX_ACCESS_TOKEN}
    networks:
      - app-network

  postgres:
    image: ghcr.io/cloudnative-pg/postgis:17-3.5
    container_name: postgis
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge