# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.14.0/deployment-apps-v1.json
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-backend-deployment
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: public-backend
  template:
    metadata:
      labels:
        app: public-backend
    spec:
      containers:
        - name: public-backend
          image: ghcr.io/2024-cmpu9010-group-3/backend-public:0.12.0@sha256:3cd940e0fe31d7779701d7f462bf6a88a8c0cfb17c05c38b74d4a38e9248e432
          resources: {}
          ports:
            - containerPort: 8080
          livenessProbe:
            exec:
              command:
                - curl
                - --fail
                - http://localhost:8080/heartbeat
            failureThreshold: 1
            periodSeconds: 30
          startupProbe:
            exec:
              command:
                - curl
                - --fail
                - http://localhost:8080/heartbeat
            failureThreshold: 30
            periodSeconds: 10
          env:
            - name: LOGIN
              valueFrom:
                secretKeyRef:
                  name: secret-magpie-db-user
                  key: LOGIN
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-magpie-db-user
                  key: PASSWORD
            - name: HOST
              valueFrom:
                secretKeyRef:
                  name: secret-magpie-db-user
                  key: HOST
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: secret-magpie-db-user
                  key: DATABASE_NAME

            - name: MAGPIE_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secret-magpie-db-user
                  key: MAGPIE_JWT_SECRET

            - name: MAGPIE_CORS_ALLOWED_ORIGINS
              value: "http://frontend-service.magpie.svc.cluster.local https://magpie.solonsstuff.com"
            - name: MAGPIE_CORS_ALLOWED_METHODS
              value: "GET, POST, PUT, DELETE, OPTIONS"
