name: Backend Private Build

on:
  push:
    branches:
      - main
    paths:
      - "Backend/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Extract package version
        id: get_version
        run: |
          VERSION=$(cat Backend/.version | tr -d '\n' | tr -d '\r')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t ghcr.io/2024-cmpu9010-group-3/backend-private:latest \
            -t ghcr.io/2024-cmpu9010-group-3/backend-private:${{ env.VERSION }} \
            --push \
            -f ./Backend/Dockerfile.private \
            ./Backend
