name: Backend Private Build

on:
  push:
    branches:
      - main
    paths:
      - "Backend/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3

      - name: Set up Go
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5
        with:
          go-version: stable

      - name: Checkout the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Extract package version
        id: get_version
        run: |
          VERSION=$(cat Backend/.version | tr -d '\n' | tr -d '\r')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t ghcr.io/2024-cmpu9010-group-3/backend-private:latest \
            -t ghcr.io/2024-cmpu9010-group-3/backend-private:${{ env.VERSION }} \
            --push \
            -f ./Backend/Dockerfile.private \
            ./Backend
