name: Build Backend Docker Image

on:
  pull_request:
    branches:
      - "backend/**"

jobs:
  build-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image for arm64 and amd64
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t backend-test-image ./Backend
