name: Frontend Tests

on:
  pull_request:
    paths:
      - "Frontend/**"

jobs:
  lint-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: Frontend
        run: npm install

      - name: Lint the code
        working-directory: Frontend
        run: npm run lint

  build-check:
    needs: lint-check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # v3

      - name: Build Docker image for amd64
        run: |
          docker buildx build --platform linux/amd64 -t frontend-test-image ./Frontend
